### ISSUE TITLE
October Sushi?!

### ISSUE THREAD

**Issue by export-mike** [sushijs/london-uk#21]

**Comment by graycodes** [comment]
Does this mean you're going to be back in the country?

**Comment by trevorah** [comment]
Yes please!

**Comment by graycodes** [comment]
Alright, I'll see what I can do!

**Comment by export-mike** [comment]
@graycodes YEAH! about 2 years later! 👍

**Comment by clare-lindley** [comment]
Yes!

**Comment by nano-monkey** [comment]
Yes please!

**Comment by graycodes** [comment]
October sushi will be on the 23rd October! I'll put up the ticketing page shortly

**Comment by export-mike** [comment]
@graycodes where's the tickets?! 
![Image](https://media3.giphy.com/media/l41lFw057lAJQMwg0/200w.webp)

**Comment by graycodes** [comment]
Here you go! https://ti.to/sushijs-ldn/2018-october

**Comment by export-mike** [comment]
see you there!

**Comment by export-mike** [comment]
are you guys doing anything else that week? meetups etc? I might be up in london for a couple of nights.

**Comment by export-mike** [comment]
@graycodes know somewhere I can work remote, I'll be travelling upto london that day and staying over for a night or two?

**Comment by trevorah** [comment]
@export-mike we've got LNUG tomorrow if you're interested?

**Comment by export-mike** [comment]
Due to poor planning I'm not going to make this one! Have a good one. :( haha Next month? :D
