### ISSUE TITLE
Meetup #4 - March 2015

### ISSUE THREAD

**Issue by clarkie** [sushijs/london-uk#5]
I'm planning on going to Life at the end of Old Street on 27th March with @basicallydan and some of the guys from @concrete-cc so thought I should open it up. 

Any other takers?

**Comment by Emigre** [comment]
Cool stuff, let's go +1

**Comment by adrianblynch** [comment]
Yesh.

**Comment by xinUmbralis** [comment]
Sounds good, I'm in!

**Comment by Emigre** [comment]
Time to close this issue, @clarkie : )

**Comment by basicallydan** [comment]
Oh shiiiiit! @clarkie I totally forgot to come along to this! Sorry! I had it in my calendar but it was a bank holiday so I guess I just didn't notice. How did it go? Planning to do it again next month?

**Comment by adrianblynch** [comment]
It was sushilious! :dancer:

We even got to pick on a Java developer! :dancers:

**Comment by basicallydan** [comment]
Aw that sounds like fun, sad I missed out :(
